services:
    flask:
        # restart: always
        build: ./controller
        command: gunicorn -w 4 -b 0.0.0.0:5000 --access-logfile ./logs/gunicorn_access_logs.txt --error-logfile ./logs/gunicorn_error_logs.txt api:app
        volumes:
            - ./controller/:/usr/src/app/
        expose:
            - 5000
    
    nginx:
        build: ./nginx
        ports:
            - 80:80
        volumes:
            - ./view/build:/usr/share/nginx/html/
            - ./nginx/logs/:/var/log/nginx/
        depends_on:
        - flask

volumes:
    static_volume: