services:
    flask:
        # restart: always
        build: ./flask-app
        command: gunicorn -w 4 -b 0.0.0.0:8000 --access-logfile ./logs/gunicorn_access_logs.txt --error-logfile ./logs/gunicorn_error_logs.txt app:app
        volumes:
            - ./flask-app/:/usr/src/app/
        expose:
            - 8000
    
    nginx:
        build: ./nginx
        ports:
            - 80:80
        volumes:
            - ./flask-app/app/static:/usr/share/nginx/html/
            - ./nginx/logs/:/var/log/nginx/
        depends_on:
        - flask

volumes:
    static_volume: